# Generated by Django 4.2.4 on 2024-05-21 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
